import '../../features/nutrition/models/recipe_model.dart';

class SampleData {
  static List<Recipe> getSampleRecipes() {
    return [
      Recipe(
        id: 'recipe_1',
        title: 'Grilled Chicken Salad',
        description: 'A fresh and healthy salad with grilled chicken breast, mixed greens, and a light vinaigrette dressing.',
        imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
        calories: 320,
        protein: 35.0,
        carbs: 12.0,
        fat: 14.0,
        prepTimeMinutes: 10,
        cookTimeMinutes: 15,
        servings: 2,
        difficulty: 'Easy',
        ingredients: [
          '2 chicken breasts (150g each)',
          '4 cups mixed salad greens',
          '1 cup cherry tomatoes',
          '1 cucumber, sliced',
          '1/4 red onion, thinly sliced',
          '2 tbsp olive oil',
          '1 tbsp balsamic vinegar',
          'Salt and pepper to taste',
        ],
        instructions: [
          'Season chicken breasts with salt and pepper.',
          'Grill chicken over medium-high heat for 6-7 minutes per side until cooked through.',
          'Let chicken rest for 5 minutes, then slice.',
          'In a large bowl, combine salad greens, tomatoes, cucumber, and red onion.',
          'Whisk together olive oil and balsamic vinegar for dressing.',
          'Top salad with sliced chicken and drizzle with dressing.',
        ],
        tags: ['lunch', 'dinner', 'healthy', 'high-protein', 'low-carb'],
        cuisine: 'Mediterranean',
        isGlutenFree: true,
        isDairyFree: true,
        createdAt: DateTime.now().subtract(const Duration(days: 30)),
      ),
      Recipe(
        id: 'recipe_2',
        title: 'Quinoa Buddha Bowl',
        description: 'Nutrient-packed bowl with quinoa, roasted vegetables, avocado, and tahini dressing.',
        imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        calories: 450,
        protein: 15.0,
        carbs: 58.0,
        fat: 18.0,
        prepTimeMinutes: 15,
        cookTimeMinutes: 25,
        servings: 1,
        difficulty: 'Medium',
        ingredients: [
          '1 cup cooked quinoa',
          '1 cup chickpeas, drained',
          '1 sweet potato, cubed',
          '1 cup broccoli florets',
          '1/2 avocado, sliced',
          '2 tbsp tahini',
          '1 tbsp lemon juice',
          '1 tsp maple syrup',
          'Smoked paprika',
        ],
        instructions: [
          'Preheat oven to 425°F (220°C).',
          'Toss sweet potato and broccoli with olive oil and paprika.',
          'Roast vegetables for 20-25 minutes until tender.',
          'Cook quinoa according to package instructions.',
          'Whisk tahini, lemon juice, maple syrup, and water for dressing.',
          'Assemble bowl: quinoa, roasted veggies, chickpeas, avocado.',
          'Drizzle with tahini dressing.',
        ],
        tags: ['lunch', 'dinner', 'healthy', 'vegan', 'vegetarian', 'bowl'],
        cuisine: 'Modern',
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: true,
        isDairyFree: true,
        createdAt: DateTime.now().subtract(const Duration(days: 28)),
      ),
      Recipe(
        id: 'recipe_3',
        title: 'Overnight Oats with Berries',
        description: 'Easy prep-ahead breakfast with oats, almond milk, chia seeds, and fresh berries.',
        imageUrl: 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?w=800',
        calories: 280,
        protein: 10.0,
        carbs: 45.0,
        fat: 8.0,
        prepTimeMinutes: 5,
        cookTimeMinutes: 0,
        servings: 1,
        difficulty: 'Easy',
        ingredients: [
          '1/2 cup rolled oats',
          '1/2 cup almond milk',
          '1/4 cup Greek yogurt',
          '1 tbsp chia seeds',
          '1 tbsp honey',
          '1/2 cup mixed berries',
          '1 tbsp sliced almonds',
        ],
        instructions: [
          'In a jar or container, combine oats, almond milk, yogurt, and chia seeds.',
          'Stir in honey and mix well.',
          'Cover and refrigerate overnight (or at least 4 hours).',
          'In the morning, top with fresh berries and sliced almonds.',
          'Enjoy cold or warm slightly if preferred.',
        ],
        tags: ['breakfast', 'healthy', 'quick', 'vegetarian', 'make-ahead'],
        cuisine: 'American',
        isVegetarian: true,
        isGlutenFree: true,
        createdAt: DateTime.now().subtract(const Duration(days: 25)),
      ),
      Recipe(
        id: 'recipe_4',
        title: 'Salmon with Asparagus',
        description: 'Pan-seared salmon fillets with lemon-garlic asparagus. High protein, keto-friendly.',
        imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
        calories: 380,
        protein: 42.0,
        carbs: 6.0,
        fat: 20.0,
        prepTimeMinutes: 10,
        cookTimeMinutes: 15,
        servings: 2,
        difficulty: 'Medium',
        ingredients: [
          '2 salmon fillets (150g each)',
          '1 bunch asparagus',
          '2 cloves garlic, minced',
          '2 tbsp olive oil',
          '1 lemon (juice and zest)',
          'Fresh dill',
          'Salt and pepper',
        ],
        instructions: [
          'Pat salmon dry and season with salt and pepper.',
          'Heat olive oil in a skillet over medium-high heat.',
          'Sear salmon skin-side up for 4 minutes, then flip and cook 3-4 minutes more.',
          'Remove salmon and set aside.',
          'In the same pan, add garlic and asparagus.',
          'Sauté for 5-7 minutes until tender-crisp.',
          'Add lemon juice and zest, toss to combine.',
          'Serve salmon over asparagus, garnish with fresh dill.',
        ],
        tags: ['dinner', 'healthy', 'high-protein', 'keto', 'low-carb'],
        cuisine: 'Mediterranean',
        isGlutenFree: true,
        isDairyFree: true,
        createdAt: DateTime.now().subtract(const Duration(days: 22)),
      ),
      Recipe(
        id: 'recipe_5',
        title: 'Avocado Toast with Egg',
        description: 'Classic breakfast with mashed avocado, poached egg, and red pepper flakes.',
        imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414395d8?w=800',
        calories: 290,
        protein: 14.0,
        carbs: 22.0,
        fat: 16.0,
        prepTimeMinutes: 5,
        cookTimeMinutes: 8,
        servings: 1,
        difficulty: 'Easy',
        ingredients: [
          '1 slice sourdough bread',
          '1/2 ripe avocado',
          '1 large egg',
          '1 tsp lemon juice',
          'Red pepper flakes',
          'Salt and pepper',
          'Microgreens for garnish',
        ],
        instructions: [
          'Toast the sourdough bread until golden brown.',
          'Mash avocado with lemon juice, salt, and pepper.',
          'Bring a pot of water to a simmer for poaching.',
          'Crack egg into a small bowl, then gently slip into simmering water.',
          'Poach for 3-4 minutes until whites are set but yolk is still runny.',
          'Spread avocado on toast, top with poached egg.',
          'Sprinkle with red pepper flakes and garnish with microgreens.',
        ],
        tags: ['breakfast', 'quick', 'healthy', 'vegetarian', 'high-protein'],
        cuisine: 'Modern',
        isVegetarian: true,
        isDairyFree: true,
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
      ),
      Recipe(
        id: 'recipe_6',
        title: 'Turkey Lettuce Wraps',
        description: 'Low-carb lettuce wraps with seasoned ground turkey, water chestnuts, and Asian flavors.',
        imageUrl: 'https://images.unsplash.com/photo-1547496502-ffa54283d2d4?w=800',
        calories: 240,
        protein: 28.0,
        carbs: 8.0,
        fat: 10.0,
        prepTimeMinutes: 10,
        cookTimeMinutes: 15,
        servings: 4,
        difficulty: 'Easy',
        ingredients: [
          '1 lb ground turkey',
          '1 can water chestnuts, diced',
          '1/4 cup hoisin sauce',
          '2 tbsp soy sauce',
          '1 tbsp rice vinegar',
          '1 tsp sesame oil',
          '2 cloves garlic, minced',
          '1 head butter lettuce',
          'Green onions for garnish',
        ],
        instructions: [
          'Brown ground turkey in a large skillet over medium heat.',
          'Add garlic and cook for 1 minute until fragrant.',
          'Stir in water chestnuts, hoisin, soy sauce, vinegar, and sesame oil.',
          'Simmer for 5 minutes until sauce thickens slightly.',
          'Separate lettuce leaves, wash and pat dry.',
          'Spoon turkey mixture into lettuce cups.',
          'Garnish with sliced green onions and serve.',
        ],
        tags: ['lunch', 'dinner', 'healthy', 'high-protein', 'low-carb', 'quick'],
        cuisine: 'Asian Fusion',
        isGlutenFree: true,
        isDairyFree: true,
        createdAt: DateTime.now().subtract(const Duration(days: 18)),
      ),
      Recipe(
        id: 'recipe_7',
        title: 'Mediterranean Chickpea Stew',
        description: 'Hearty vegetarian stew with chickpeas, tomatoes, spinach, and Mediterranean spices.',
        imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800',
        calories: 340,
        protein: 14.0,
        carbs: 48.0,
        fat: 12.0,
        prepTimeMinutes: 10,
        cookTimeMinutes: 25,
        servings: 4,
        difficulty: 'Easy',
        ingredients: [
          '2 cans chickpeas, drained',
          '1 can diced tomatoes',
          '4 cups fresh spinach',
          '1 onion, diced',
          '3 cloves garlic, minced',
          '2 tsp cumin',
          '1 tsp paprika',
          '1/2 tsp cinnamon',
          '2 tbsp olive oil',
          'Vegetable broth',
        ],
        instructions: [
          'Heat olive oil in a large pot over medium heat.',
          'Sauté onion until soft, about 5 minutes.',
          'Add garlic and spices, cook for 1 minute until fragrant.',
          'Add chickpeas, tomatoes, and enough broth to cover.',
          'Bring to a simmer and cook for 15 minutes.',
          'Stir in spinach and cook until wilted.',
          'Serve hot with crusty bread or over rice.',
        ],
        tags: ['dinner', 'healthy', 'vegan', 'vegetarian', 'comfort'],
        cuisine: 'Mediterranean',
        isVegetarian: true,
        isVegan: true,
        isGlutenFree: true,
        isDairyFree: true,
        createdAt: DateTime.now().subtract(const Duration(days: 15)),
      ),
      Recipe(
        id: 'recipe_8',
        title: 'Protein Smoothie Bowl',
        description: 'Thick and creamy smoothie bowl with protein powder, banana, and tons of toppings.',
        imageUrl: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=800',
        calories: 310,
        protein: 25.0,
        carbs: 42.0,
        fat: 6.0,
        prepTimeMinutes: 5,
        cookTimeMinutes: 0,
        servings: 1,
        difficulty: 'Easy',
        ingredients: [
          '1 scoop vanilla protein powder',
          '1 frozen banana',
          '1/2 cup frozen berries',
          '1/2 cup almond milk',
          '1 tbsp chia seeds',
          'Toppings: granola, coconut, fresh fruit',
        ],
        instructions: [
          'Add protein powder, frozen banana, berries, and almond milk to blender.',
          'Blend until smooth and thick, adding more milk if needed.',
          'Pour into a bowl.',
          'Arrange toppings artistically.',
          'Sprinkle chia seeds on top.',
          'Serve immediately with a spoon.',
        ],
        tags: ['breakfast', 'healthy', 'quick', 'vegetarian', 'high-protein'],
        cuisine: 'Modern',
        isVegetarian: true,
        isGlutenFree: true,
        isDairyFree: true,
        createdAt: DateTime.now().subtract(const Duration(days: 12)),
      ),
    ];
  }

  // Call this during app initialization to seed sample data
  static Future<void> seedSampleRecipes() async {
    // This would typically call the repository to add recipes
    // For now, recipes are stored in Firestore manually or via admin panel
    // In production, you might want to check if recipes exist first
  }
}
