// Run: dart run tools/seed_data.dart
// Seeds all Firestore collections via Firebase REST API
// First: get a token with `firebase login` then copy your ID token

import 'dart:convert';

const projectId = 'better-you-f6919';

// Replace with token from: firebase auth:export or use Firebase Console to manually import
// For quick seeding, open Firebase Console > Firestore > Import JSON
// and paste the output of this script

void main() async {
  // ignore: avoid_print
  print('🌱 Better You Firestore Seeder');
  final data = buildSeedData();
  // ignore: avoid_print
  print(jsonEncode(data));
  // ignore: avoid_print
  print('\n✅ Copy output above to seed_data.json, then import in Firebase Console');
}

Map<String, dynamic> buildSeedData() {
  return {
    'recipes': _recipes,
    'workout_plans': _workouts,
    'nutrition_tips': _tips,
    'coaches': _coaches,
    'doctors': _doctors,
  };
}

final _recipes = [
  {'id': 'r001', 'title': 'Greek Yogurt Parfait', 'description': 'Creamy Greek yogurt layered with fresh berries and granola.', 'imageUrl': 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800', 'calories': 320, 'protein': 18.0, 'carbs': 42.0, 'fat': 6.0, 'prepTimeMinutes': 5, 'cookTimeMinutes': 0, 'servings': 1, 'difficulty': 'Easy', 'cuisine': 'Mediterranean', 'isVegetarian': true, 'isVegan': false, 'isGlutenFree': true, 'isDairyFree': false, 'tags': ['breakfast', 'high-protein', 'quick'], 'ingredients': ['200g Greek yogurt', '1/2 cup mixed berries', '1/4 cup granola', '1 tbsp honey'], 'instructions': ['Layer yogurt in bowl', 'Add berries', 'Sprinkle granola', 'Drizzle honey']},
  {'id': 'r002', 'title': 'Avocado Toast with Poached Eggs', 'description': 'Whole grain toast with smashed avocado and poached eggs.', 'imageUrl': 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800', 'calories': 420, 'protein': 22.0, 'carbs': 35.0, 'fat': 22.0, 'prepTimeMinutes': 5, 'cookTimeMinutes': 10, 'servings': 1, 'difficulty': 'Medium', 'cuisine': 'American', 'isVegetarian': true, 'isVegan': false, 'isGlutenFree': false, 'isDairyFree': true, 'tags': ['breakfast', 'high-protein'], 'ingredients': ['2 slices whole grain bread', '1 ripe avocado', '2 eggs', 'Salt & pepper', '1 tsp lemon juice'], 'instructions': ['Toast bread', 'Mash avocado with lemon and salt', 'Poach eggs 3-4 min', 'Assemble and season']},
  {'id': 'r003', 'title': 'Overnight Oats', 'description': 'No-cook oats with almond milk, banana and peanut butter.', 'imageUrl': 'https://images.unsplash.com/photo-1571748982800-fa51082c2224?w=800', 'calories': 380, 'protein': 12.0, 'carbs': 58.0, 'fat': 10.0, 'prepTimeMinutes': 5, 'cookTimeMinutes': 0, 'servings': 1, 'difficulty': 'Easy', 'cuisine': 'American', 'isVegetarian': true, 'isVegan': true, 'isGlutenFree': false, 'isDairyFree': true, 'tags': ['breakfast', 'vegan', 'meal-prep'], 'ingredients': ['1/2 cup rolled oats', '1 cup almond milk', '1 banana', '2 tbsp peanut butter', '1 tbsp maple syrup'], 'instructions': ['Mix oats and almond milk', 'Add syrup and vanilla', 'Refrigerate overnight', 'Top with banana and PB']},
  {'id': 'r004', 'title': 'Spinach Mushroom Omelette', 'description': 'Fluffy 3-egg omelette with sauteed spinach and mushrooms.', 'imageUrl': 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=800', 'calories': 290, 'protein': 26.0, 'carbs': 6.0, 'fat': 18.0, 'prepTimeMinutes': 5, 'cookTimeMinutes': 8, 'servings': 1, 'difficulty': 'Easy', 'cuisine': 'French', 'isVegetarian': true, 'isVegan': false, 'isGlutenFree': true, 'isDairyFree': false, 'tags': ['breakfast', 'high-protein', 'keto'], 'ingredients': ['3 eggs', '1 cup spinach', '1/2 cup mushrooms', '2 tbsp feta', '1 tbsp olive oil'], 'instructions': ['Saute mushrooms 3 min', 'Add spinach until wilted', 'Beat eggs, pour into pan', 'Add filling and fold']},
  {'id': 'r005', 'title': 'Banana Protein Pancakes', 'description': 'Fluffy high-protein pancakes with banana and protein powder.', 'imageUrl': 'https://images.unsplash.com/photo-1506459225024-1428097a7e18?w=800', 'calories': 350, 'protein': 30.0, 'carbs': 40.0, 'fat': 7.0, 'prepTimeMinutes': 5, 'cookTimeMinutes': 10, 'servings': 2, 'difficulty': 'Easy', 'cuisine': 'American', 'isVegetarian': true, 'isVegan': false, 'isGlutenFree': true, 'isDairyFree': false, 'tags': ['breakfast', 'high-protein', 'post-workout'], 'ingredients': ['2 bananas', '2 eggs', '1 scoop vanilla protein powder', '1/2 tsp baking powder', '1 tsp cinnamon'], 'instructions': ['Mash bananas', 'Mix in eggs and protein powder', 'Cook on non-stick pan 2 min per side']},
  {'id': 'r006', 'title': 'Chia Seed Pudding', 'description': 'Coconut milk chia pudding with mango and toasted coconut.', 'imageUrl': 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800', 'calories': 280, 'protein': 8.0, 'carbs': 32.0, 'fat': 14.0, 'prepTimeMinutes': 5, 'cookTimeMinutes': 0, 'servings': 1, 'difficulty': 'Easy', 'cuisine': 'Tropical', 'isVegetarian': true, 'isVegan': true, 'isGlutenFree': true, 'isDairyFree': true, 'tags': ['breakfast', 'vegan', 'gluten-free'], 'ingredients': ['3 tbsp chia seeds', '1 cup coconut milk', '1 mango diced', '1 tbsp agave'], 'instructions': ['Mix chia and coconut milk', 'Refrigerate 4 hours', 'Top with mango']},
  {'id': 'r007', 'title': 'Smoothie Bowl', 'description': 'Thick acai smoothie bowl with fresh fruit and seeds.', 'imageUrl': 'https://images.unsplash.com/photo-1511690078903-71dc5a49f5e3?w=800', 'calories': 340, 'protein': 10.0, 'carbs': 62.0, 'fat': 8.0, 'prepTimeMinutes': 10, 'cookTimeMinutes': 0, 'servings': 1, 'difficulty': 'Easy', 'cuisine': 'Brazilian', 'isVegetarian': true, 'isVegan': true, 'isGlutenFree': true, 'isDairyFree': true, 'tags': ['breakfast', 'vegan', 'antioxidant'], 'ingredients': ['100g frozen acai', '1 frozen banana', '1/2 cup almond milk', 'Kiwi, blueberries, granola toppings'], 'instructions': ['Blend acai, banana, almond milk until thick', 'Pour into bowl', 'Arrange toppings']},
  {'id': 'r008', 'title': 'Turkish Menemen', 'description': 'Spiced tomato and pepper egg scramble.', 'imageUrl': 'https://images.unsplash.com/photo-1619740455993-9d622fc45b1b?w=800', 'calories': 260, 'protein': 18.0, 'carbs': 14.0, 'fat': 14.0, 'prepTimeMinutes': 5, 'cookTimeMinutes': 15, 'servings': 2, 'difficulty': 'Easy', 'cuisine': 'Turkish', 'isVegetarian': true, 'isVegan': false, 'isGlutenFree': true, 'isDairyFree': true, 'tags': ['breakfast', 'mediterranean', 'high-protein'], 'ingredients': ['4 eggs', '2 tomatoes', '1 green pepper', '1 onion', '2 tbsp olive oil', '1 tsp cumin'], 'instructions': ['Saute onion and pepper 5 min', 'Add tomatoes and cumin', 'Crack eggs in and scramble gently']},
  {'id': 'r009', 'title': 'Peanut Butter Banana Toast', 'description': 'Power breakfast with natural peanut butter and banana.', 'imageUrl': 'https://images.unsplash.com/photo-1618090584176-7132b9911657?w=800', 'calories': 390, 'protein': 14.0, 'carbs': 52.0, 'fat': 16.0, 'prepTimeMinutes': 3, 'cookTimeMinutes': 2, 'servings': 1, 'difficulty': 'Easy', 'cuisine': 'American', 'isVegetarian': true, 'isVegan': true, 'isGlutenFree': false, 'isDairyFree': true, 'tags': ['breakfast', 'quick', 'energy'], 'ingredients': ['2 slices whole grain bread', '2 tbsp peanut butter', '1 banana', '1 tsp honey'], 'instructions': ['Toast bread', 'Spread PB', 'Layer banana', 'Drizzle honey']},
  {'id': 'r010', 'title': 'Cottage Cheese Bowl', 'description': 'High-protein cottage cheese with peaches and walnuts.', 'imageUrl': 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=800', 'calories': 300, 'protein': 24.0, 'carbs': 28.0, 'fat': 10.0, 'prepTimeMinutes': 3, 'cookTimeMinutes': 0, 'servings': 1, 'difficulty': 'Easy', 'cuisine': 'American', 'isVegetarian': true, 'isVegan': false, 'isGlutenFree': true, 'isDairyFree': false, 'tags': ['breakfast', 'high-protein', 'low-carb'], 'ingredients': ['1 cup cottage cheese', '1 peach diced', '2 tbsp walnuts', '1 tsp honey'], 'instructions': ['Spoon cottage cheese into bowl', 'Top with peach and walnuts', 'Drizzle honey']},
  {'id': 'r011', 'title': 'Grilled Chicken Caesar Salad', 'description': 'Classic Caesar with grilled chicken, romaine and parmesan.', 'imageUrl': 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800', 'calories': 420, 'protein': 40.0, 'carbs': 18.0, 'fat': 22.0, 'prepTimeMinutes': 10, 'cookTimeMinutes': 15, 'servings': 2, 'difficulty': 'Easy', 'cuisine': 'American', 'isVegetarian': false, 'isVegan': false, 'isGlutenFree': false, 'isDairyFree': false, 'tags': ['lunch', 'high-protein', 'salad'], 'ingredients': ['2 chicken breasts', '1 romaine head', '50g parmesan', '1 cup croutons', '3 tbsp Caesar dressing'], 'instructions': ['Grill chicken 6-7 min per side', 'Chop romaine', 'Slice chicken', 'Toss with dressing and toppings']},
  {'id': 'r012', 'title': 'Quinoa Buddha Bowl', 'description': 'Quinoa with roasted veggies, chickpeas and tahini sauce.', 'imageUrl': 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800', 'calories': 480, 'protein': 18.0, 'carbs': 62.0, 'fat': 16.0, 'prepTimeMinutes': 10, 'cookTimeMinutes': 25, 'servings': 2, 'difficulty': 'Easy', 'cuisine': 'Fusion', 'isVegetarian': true, 'isVegan': true, 'isGlutenFree': true, 'isDairyFree': true, 'tags': ['lunch', 'vegan', 'meal-prep'], 'ingredients': ['1 cup quinoa', '1 can chickpeas', '1 sweet potato', '3 tbsp tahini', '2 tbsp lemon juice'], 'instructions': ['Cook quinoa', 'Roast chickpeas and potato 20 min', 'Make tahini sauce', 'Assemble bowls']},
  {'id': 'r013', 'title': 'Lentil Soup', 'description': 'Hearty red lentil soup with cumin, turmeric and lemon.', 'imageUrl': 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800', 'calories': 320, 'protein': 18.0, 'carbs': 52.0, 'fat': 5.0, 'prepTimeMinutes': 10, 'cookTimeMinutes': 30, 'servings': 4, 'difficulty': 'Easy', 'cuisine': 'Middle Eastern', 'isVegetarian': true, 'isVegan': true, 'isGlutenFree': true, 'isDairyFree': true, 'tags': ['lunch', 'vegan', 'high-fiber', 'meal-prep'], 'ingredients': ['2 cups red lentils', '1 onion', '3 garlic cloves', '1 tsp cumin', '1 tsp turmeric', '1 lemon'], 'instructions': ['Saute onion and garlic', 'Add lentils, broth and spices', 'Simmer 25 min', 'Blend half, add lemon']},
  {'id': 'r014', 'title': 'Turkey Wrap', 'description': 'Whole grain wrap with turkey, hummus and fresh veggies.', 'imageUrl': 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800', 'calories': 450, 'protein': 32.0, 'carbs': 42.0, 'fat': 16.0, 'prepTimeMinutes': 8, 'cookTimeMinutes': 0, 'servings': 1, 'difficulty': 'Easy', 'cuisine': 'American', 'isVegetarian': false, 'isVegan': false, 'isGlutenFree': false, 'isDairyFree': true, 'tags': ['lunch', 'high-protein', 'quick'], 'ingredients': ['1 whole grain tortilla', '150g turkey slices', '2 tbsp hummus', '1/2 avocado', 'Lettuce, tomato, cucumber'], 'instructions': ['Spread hummus', 'Layer turkey, avocado and veggies', 'Roll and slice']},
  {'id': 'r015', 'title': 'Salmon Poke Bowl', 'description': 'Hawaiian bowl with fresh salmon, edamame and sesame rice.', 'imageUrl': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800', 'calories': 520, 'protein': 36.0, 'carbs': 58.0, 'fat': 14.0, 'prepTimeMinutes': 15, 'cookTimeMinutes': 20, 'servings': 2, 'difficulty': 'Medium', 'cuisine': 'Hawaiian', 'isVegetarian': false, 'isVegan': false, 'isGlutenFree': true, 'isDairyFree': true, 'tags': ['lunch', 'high-protein', 'omega-3'], 'ingredients': ['300g sushi-grade salmon', '1.5 cups sushi rice', '1 cup edamame', '1 avocado', '2 tbsp soy sauce', '1 tbsp sesame oil'], 'instructions': ['Cook sushi rice', 'Dice salmon, marinate in soy and sesame', 'Arrange bowls', 'Sprinkle sesame seeds']},
  {'id': 'r016', 'title': 'Baked Salmon with Asparagus', 'description': 'Herb-crusted salmon with roasted asparagus and lemon butter.', 'imageUrl': 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800', 'calories': 440, 'protein': 42.0, 'carbs': 8.0, 'fat': 26.0, 'prepTimeMinutes': 10, 'cookTimeMinutes': 20, 'servings': 2, 'difficulty': 'Easy', 'cuisine': 'American', 'isVegetarian': false, 'isVegan': false, 'isGlutenFree': true, 'isDairyFree': false, 'tags': ['dinner', 'high-protein', 'omega-3', 'keto'], 'ingredients': ['2 salmon fillets', '1 bunch asparagus', '2 tbsp butter', '2 garlic cloves', '1 lemon', 'Fresh dill'], 'instructions': ['Preheat oven to 200C', 'Place salmon and asparagus on baking sheet', 'Spread garlic butter on salmon', 'Bake 18-20 min']},
  {'id': 'r017', 'title': 'Chicken Tikka Masala', 'description': 'Creamy tomato-based curry with marinated chicken.', 'imageUrl': 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800', 'calories': 520, 'protein': 38.0, 'carbs': 32.0, 'fat': 24.0, 'prepTimeMinutes': 20, 'cookTimeMinutes': 30, 'servings': 4, 'difficulty': 'Medium', 'cuisine': 'Indian', 'isVegetarian': false, 'isVegan': false, 'isGlutenFree': true, 'isDairyFree': false, 'tags': ['dinner', 'high-protein', 'indian'], 'ingredients': ['700g chicken breast', '1 can crushed tomatoes', '1 cup cream', '1 onion', '4 garlic cloves', '1 tbsp garam masala', '1 tsp turmeric'], 'instructions': ['Marinate chicken in yogurt and spices', 'Saute onion, garlic, ginger', 'Add tomatoes and spices', 'Add chicken, cook through', 'Stir in cream']},
  {'id': 'r018', 'title': 'Spaghetti Bolognese', 'description': 'Classic Italian meat sauce with tomatoes and herbs.', 'imageUrl': 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800', 'calories': 580, 'protein': 36.0, 'carbs': 64.0, 'fat': 18.0, 'prepTimeMinutes': 15, 'cookTimeMinutes': 45, 'servings': 4, 'difficulty': 'Easy', 'cuisine': 'Italian', 'isVegetarian': false, 'isVegan': false, 'isGlutenFree': false, 'isDairyFree': true, 'tags': ['dinner', 'italian', 'family'], 'ingredients': ['400g ground beef', '400g spaghetti', '1 can crushed tomatoes', '1 onion', '3 garlic cloves', 'Red wine', 'Italian herbs'], 'instructions': ['Brown beef with onion and garlic', 'Add tomatoes and wine', 'Simmer 40 min', 'Cook pasta and serve']},
  {'id': 'r019', 'title': 'Vegetable Curry', 'description': 'Coconut milk curry with chickpeas, sweet potato and spinach.', 'imageUrl': 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800', 'calories': 420, 'protein': 14.0, 'carbs': 58.0, 'fat': 16.0, 'prepTimeMinutes': 10, 'cookTimeMinutes': 25, 'servings': 4, 'difficulty': 'Easy', 'cuisine': 'Indian', 'isVegetarian': true, 'isVegan': true, 'isGlutenFree': true, 'isDairyFree': true, 'tags': ['dinner', 'vegan', 'meal-prep'], 'ingredients': ['1 can chickpeas', '1 sweet potato', '400ml coconut milk', '2 cups spinach', '2 tbsp curry powder', '1 can tomatoes'], 'instructions': ['Saute onion and garlic', 'Add curry powder', 'Add potato, tomatoes and coconut milk', 'Simmer 15 min', 'Add chickpeas and spinach']},
  {'id': 'r020', 'title': 'Shakshuka', 'description': 'Eggs poached in spiced tomato sauce with feta.', 'imageUrl': 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=800', 'calories': 320, 'protein': 20.0, 'carbs': 22.0, 'fat': 16.0, 'prepTimeMinutes': 5, 'cookTimeMinutes': 20, 'servings': 2, 'difficulty': 'Easy', 'cuisine': 'Middle Eastern', 'isVegetarian': true, 'isVegan': false, 'isGlutenFree': true, 'isDairyFree': false, 'tags': ['dinner', 'vegetarian', 'one-pan'], 'ingredients': ['4 eggs', '1 can crushed tomatoes', '1 red pepper', '1 onion', '1 tsp cumin', '60g feta', 'Fresh parsley'], 'instructions': ['Saute onion and pepper', 'Add spices and tomatoes, simmer 10 min', 'Make wells, crack eggs in', 'Cover and cook 6 min', 'Top with feta']},
  {'id': 'r021', 'title': 'Green Power Smoothie', 'description': 'Spinach, banana and mango smoothie with protein.', 'imageUrl': 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=800', 'calories': 280, 'protein': 20.0, 'carbs': 42.0, 'fat': 4.0, 'prepTimeMinutes': 5, 'cookTimeMinutes': 0, 'servings': 1, 'difficulty': 'Easy', 'cuisine': 'American', 'isVegetarian': true, 'isVegan': true, 'isGlutenFree': true, 'isDairyFree': true, 'tags': ['smoothie', 'vegan', 'high-protein'], 'ingredients': ['2 cups spinach', '1 frozen banana', '1 cup frozen mango', '1 scoop vanilla protein', '1.5 cups almond milk'], 'instructions': ['Add all to blender', 'Blend until smooth', 'Serve immediately']},
  {'id': 'r022', 'title': 'Berry Protein Smoothie', 'description': 'Mixed berry smoothie with Greek yogurt and oats.', 'imageUrl': 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800', 'calories': 320, 'protein': 22.0, 'carbs': 48.0, 'fat': 5.0, 'prepTimeMinutes': 5, 'cookTimeMinutes': 0, 'servings': 1, 'difficulty': 'Easy', 'cuisine': 'American', 'isVegetarian': true, 'isVegan': false, 'isGlutenFree': true, 'isDairyFree': false, 'tags': ['smoothie', 'high-protein', 'breakfast'], 'ingredients': ['1 cup frozen berries', '1/2 cup Greek yogurt', '1/4 cup oats', '1 cup milk', '1 tbsp honey'], 'instructions': ['Add all to blender', 'Blend until creamy']},
  {'id': 'r023', 'title': 'Chocolate PB Smoothie', 'description': 'Chocolate and peanut butter protein shake.', 'imageUrl': 'https://images.unsplash.com/photo-1572490122747-3e9b81b50b09?w=800', 'calories': 380, 'protein': 28.0, 'carbs': 38.0, 'fat': 14.0, 'prepTimeMinutes': 5, 'cookTimeMinutes': 0, 'servings': 1, 'difficulty': 'Easy', 'cuisine': 'American', 'isVegetarian': true, 'isVegan': false, 'isGlutenFree': true, 'isDairyFree': false, 'tags': ['smoothie', 'high-protein', 'post-workout'], 'ingredients': ['1 frozen banana', '2 tbsp peanut butter', '1 scoop chocolate protein', '1 tbsp cocoa powder', '1.5 cups milk'], 'instructions': ['Add all to blender', 'Blend until thick and smooth']},
  {'id': 'r024', 'title': 'Apple with Almond Butter', 'description': 'Simple snack with crisp apple and natural almond butter.', 'imageUrl': 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=800', 'calories': 200, 'protein': 5.0, 'carbs': 28.0, 'fat': 9.0, 'prepTimeMinutes': 2, 'cookTimeMinutes': 0, 'servings': 1, 'difficulty': 'Easy', 'cuisine': 'American', 'isVegetarian': true, 'isVegan': true, 'isGlutenFree': true, 'isDairyFree': true, 'tags': ['snack', 'vegan', 'quick'], 'ingredients': ['1 apple', '2 tbsp almond butter'], 'instructions': ['Slice apple', 'Serve with almond butter']},
  {'id': 'r025', 'title': 'Protein Energy Balls', 'description': 'No-bake oat and peanut butter energy balls.', 'imageUrl': 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800', 'calories': 180, 'protein': 8.0, 'carbs': 22.0, 'fat': 8.0, 'prepTimeMinutes': 15, 'cookTimeMinutes': 0, 'servings': 12, 'difficulty': 'Easy', 'cuisine': 'American', 'isVegetarian': true, 'isVegan': false, 'isGlutenFree': false, 'isDairyFree': false, 'tags': ['snack', 'high-protein', 'meal-prep'], 'ingredients': ['1 cup rolled oats', '1/2 cup peanut butter', '1/3 cup honey', '1/2 cup dark chocolate chips', '2 tbsp flaxseed'], 'instructions': ['Mix all ingredients', 'Refrigerate 30 min', 'Roll into 12 balls']},
  {'id': 'r026', 'title': 'Hummus with Veggie Sticks', 'description': 'Creamy hummus with colorful raw vegetable dippers.', 'imageUrl': 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800', 'calories': 160, 'protein': 7.0, 'carbs': 18.0, 'fat': 7.0, 'prepTimeMinutes': 5, 'cookTimeMinutes': 0, 'servings': 2, 'difficulty': 'Easy', 'cuisine': 'Mediterranean', 'isVegetarian': true, 'isVegan': true, 'isGlutenFree': true, 'isDairyFree': true, 'tags': ['snack', 'vegan', 'no-cook'], 'ingredients': ['4 tbsp hummus', '1 carrot', '1 cucumber', '1 bell pepper', '4 celery stalks'], 'instructions': ['Arrange vegetables on plate', 'Serve with hummus']},
  {'id': 'r027', 'title': 'Grilled Chicken with Sweet Potato', 'description': 'Grilled chicken thighs with roasted sweet potato.', 'imageUrl': 'https://images.unsplash.com/photo-1598103442097-8b74394b95c7?w=800', 'calories': 480, 'protein': 38.0, 'carbs': 42.0, 'fat': 16.0, 'prepTimeMinutes': 10, 'cookTimeMinutes': 30, 'servings': 2, 'difficulty': 'Easy', 'cuisine': 'American', 'isVegetarian': false, 'isVegan': false, 'isGlutenFree': true, 'isDairyFree': true, 'tags': ['dinner', 'high-protein', 'meal-prep'], 'ingredients': ['4 chicken thighs', '2 sweet potatoes', '2 tbsp olive oil', '1 tsp paprika', '1 tsp garlic powder'], 'instructions': ['Preheat oven 200C', 'Roast sweet potatoes 20 min', 'Grill chicken 7 min per side', 'Serve together']},
  {'id': 'r028', 'title': 'Black Bean Tacos', 'description': 'Crispy corn tortillas with spiced black beans and salsa.', 'imageUrl': 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800', 'calories': 380, 'protein': 14.0, 'carbs': 58.0, 'fat': 10.0, 'prepTimeMinutes': 10, 'cookTimeMinutes': 10, 'servings': 2, 'difficulty': 'Easy', 'cuisine': 'Mexican', 'isVegetarian': true, 'isVegan': false, 'isGlutenFree': true, 'isDairyFree': false, 'tags': ['lunch', 'vegetarian', 'mexican'], 'ingredients': ['1 can black beans', '4 corn tortillas', '1 cup salsa', '1 avocado', '1/2 cup Greek yogurt', '1 lime'], 'instructions': ['Season beans with cumin and lime', 'Warm tortillas', 'Fill with beans', 'Top with salsa and avocado']},
  {'id': 'r029', 'title': 'Tofu Stir-Fry', 'description': 'Crispy tofu with snap peas in ginger-miso sauce.', 'imageUrl': 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800', 'calories': 360, 'protein': 22.0, 'carbs': 32.0, 'fat': 16.0, 'prepTimeMinutes': 15, 'cookTimeMinutes': 15, 'servings': 2, 'difficulty': 'Medium', 'cuisine': 'Japanese', 'isVegetarian': true, 'isVegan': true, 'isGlutenFree': true, 'isDairyFree': true, 'tags': ['dinner', 'vegan', 'asian'], 'ingredients': ['400g firm tofu', '1 cup snap peas', '1 bell pepper', '2 tbsp miso paste', '2 tbsp soy sauce', '1 tsp ginger'], 'instructions': ['Bake tofu cubes 200C 20 min', 'Stir-fry vegetables 5 min', 'Add tofu and sauce, toss 2 min']},
  {'id': 'r030', 'title': 'Lemon Herb Chicken', 'description': 'Pan-seared chicken with lemon, garlic and fresh herbs.', 'imageUrl': 'https://images.unsplash.com/photo-1598103442097-8b74394b95c7?w=800', 'calories': 340, 'protein': 42.0, 'carbs': 4.0, 'fat': 16.0, 'prepTimeMinutes': 5, 'cookTimeMinutes': 20, 'servings': 2, 'difficulty': 'Easy', 'cuisine': 'American', 'isVegetarian': false, 'isVegan': false, 'isGlutenFree': true, 'isDairyFree': true, 'tags': ['dinner', 'high-protein', 'keto', 'quick'], 'ingredients': ['2 chicken breasts', '3 garlic cloves', '1 lemon', '2 tbsp olive oil', 'Fresh thyme', 'Fresh rosemary'], 'instructions': ['Season chicken', 'Sear 6-7 min per side', 'Add garlic and herbs', 'Finish with lemon juice']},
];

final _workouts = [
  {'id': 'w001', 'name': '30-Day Beginner Fat Loss', 'goal': 'weight_loss', 'level': 'beginner', 'durationWeeks': 4, 'sessionsPerWeek': 3, 'isPremium': false, 'imageUrl': 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800', 'description': 'A progressive plan for complete beginners to build fitness and burn fat.', 'exercises': ['Walking 30 min', 'Bodyweight squats 3x15', 'Push-ups 3x10', 'Plank 30s x3', 'Lunges 3x12']},
  {'id': 'w002', 'name': 'Muscle Builder 12-Week', 'goal': 'muscle_gain', 'level': 'intermediate', 'durationWeeks': 12, 'sessionsPerWeek': 4, 'isPremium': true, 'imageUrl': 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800', 'description': 'Progressive overload program to build lean muscle mass.', 'exercises': ['Bench Press 4x8', 'Squats 4x8', 'Deadlift 3x6', 'Pull-ups 3x10', 'Overhead Press 3x10']},
  {'id': 'w003', 'name': 'HIIT Cardio Blast', 'goal': 'endurance', 'level': 'intermediate', 'durationWeeks': 6, 'sessionsPerWeek': 4, 'isPremium': false, 'imageUrl': 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 'description': 'High-intensity intervals to torch calories and improve cardio.', 'exercises': ['Jump squats 40s', 'Burpees 40s', 'Mountain climbers 40s', 'High knees 40s', 'Rest 20s - repeat 6x']},
  {'id': 'w004', 'name': 'Yoga & Flexibility Flow', 'goal': 'flexibility', 'level': 'beginner', 'durationWeeks': 8, 'sessionsPerWeek': 5, 'isPremium': false, 'imageUrl': 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800', 'description': 'Daily yoga to improve flexibility, posture and reduce stress.', 'exercises': ['Sun Salutation 5x', 'Warrior sequence', 'Hip opener flow', 'Forward folds', 'Savasana 10 min']},
  {'id': 'w005', 'name': 'Home Bodyweight Shred', 'goal': 'weight_loss', 'level': 'intermediate', 'durationWeeks': 8, 'sessionsPerWeek': 5, 'isPremium': false, 'imageUrl': 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800', 'description': 'Zero equipment home workout for fat loss.', 'exercises': ['Push-ups 4x15', 'Jump squats 4x15', 'Tricep dips 3x12', 'Glute bridges 4x20', 'Bicycle crunches 3x20']},
  {'id': 'w006', 'name': 'Powerlifting Foundation', 'goal': 'strength', 'level': 'advanced', 'durationWeeks': 16, 'sessionsPerWeek': 4, 'isPremium': true, 'imageUrl': 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800', 'description': 'Build maximal strength in squat, bench and deadlift.', 'exercises': ['Squat 5x5', 'Bench Press 5x5', 'Deadlift 3x3', 'Rows and dips accessory']},
  {'id': 'w007', 'name': 'Running for Beginners', 'goal': 'endurance', 'level': 'beginner', 'durationWeeks': 8, 'sessionsPerWeek': 3, 'isPremium': false, 'imageUrl': 'https://images.unsplash.com/photo-1461897104016-0b3b00cc81ee?w=800', 'description': 'Couch to 5K style program to build a running habit.', 'exercises': ['Week 1: Walk 2 min/Run 1 min x8', 'Week 4: Run 5 min x4', 'Week 8: Run 30 min continuous']},
  {'id': 'w008', 'name': 'Core & Abs Sculptor', 'goal': 'toning', 'level': 'beginner', 'durationWeeks': 6, 'sessionsPerWeek': 5, 'isPremium': false, 'imageUrl': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800', 'description': 'Daily core routine to strengthen abs, obliques and lower back.', 'exercises': ['Plank 60s x3', 'Dead bug 3x12', 'Russian twists 3x20', 'Leg raises 3x15', 'Bird dog 3x12']},
  {'id': 'w009', 'name': 'Upper Body Strength', 'goal': 'muscle_gain', 'level': 'intermediate', 'durationWeeks': 8, 'sessionsPerWeek': 3, 'isPremium': true, 'imageUrl': 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800', 'description': 'Focused upper body targeting chest, back, shoulders and arms.', 'exercises': ['Pull-ups 4x8', 'Dumbbell Press 4x10', 'Cable Rows 4x12', 'Lateral Raises 3x15', 'Bicep Curls 3x12']},
  {'id': 'w010', 'name': 'Glutes & Legs Builder', 'goal': 'muscle_gain', 'level': 'intermediate', 'durationWeeks': 8, 'sessionsPerWeek': 3, 'isPremium': true, 'imageUrl': 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800', 'description': 'Dedicated lower body program for strong glutes and legs.', 'exercises': ['Barbell Squat 4x8', 'Romanian Deadlift 4x10', 'Hip Thrust 4x12', 'Leg Press 3x15', 'Calf Raises 4x20']},
  {'id': 'w011', 'name': 'Pilates for Posture', 'goal': 'flexibility', 'level': 'beginner', 'durationWeeks': 6, 'sessionsPerWeek': 4, 'isPremium': false, 'imageUrl': 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800', 'description': 'Pilates to fix posture, relieve back pain and build core.', 'exercises': ['Hundred exercise', 'Roll-ups 10x', 'Single leg circles', 'Swimming 30s', 'Child pose stretch']},
  {'id': 'w012', 'name': 'Athletic Performance', 'goal': 'performance', 'level': 'advanced', 'durationWeeks': 12, 'sessionsPerWeek': 5, 'isPremium': true, 'imageUrl': 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800', 'description': 'Sport-specific conditioning to improve speed, agility and power.', 'exercises': ['Sprint intervals 8x100m', 'Box jumps 4x8', 'Agility ladder drills', 'Plyometric push-ups']},
  {'id': 'w013', 'name': 'Lean & Toned 8-Week', 'goal': 'toning', 'level': 'beginner', 'durationWeeks': 8, 'sessionsPerWeek': 4, 'isPremium': false, 'imageUrl': 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800', 'description': 'Combination of strength and cardio for a lean toned physique.', 'exercises': ['Dumbbell circuits 30 min', 'Steady-state cardio 20 min', 'Full-body stretching 10 min']},
  {'id': 'w014', 'name': 'Senior Wellness Plan', 'goal': 'general_fitness', 'level': 'beginner', 'durationWeeks': 12, 'sessionsPerWeek': 3, 'isPremium': false, 'imageUrl': 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 'description': 'Low-impact exercise for adults over 50 to maintain strength and mobility.', 'exercises': ['Chair squats 3x12', 'Wall push-ups 3x10', 'Balance exercises', 'Walking 20 min']},
  {'id': 'w015', 'name': 'Desk Worker De-Stress', 'goal': 'flexibility', 'level': 'beginner', 'durationWeeks': 4, 'sessionsPerWeek': 5, 'isPremium': false, 'imageUrl': 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800', 'description': 'Daily 20-minute routine to undo the damage of sitting all day.', 'exercises': ['Chest openers', 'Hip flexor stretch 2 min each', 'Shoulder rolls', 'Spinal twists', 'Forward fold']},
  {'id': 'w016', 'name': '21-Day Habit Reset', 'goal': 'general_fitness', 'level': 'beginner', 'durationWeeks': 3, 'sessionsPerWeek': 7, 'isPremium': false, 'imageUrl': 'https://images.unsplash.com/photo-1461897104016-0b3b00cc81ee?w=800', 'description': 'Build sustainable exercise habits with 20 min daily commitment.', 'exercises': ['Day 1-7: Walking 20 min', 'Day 8-14: Walking + 10 min bodyweight', 'Day 15-21: Full 20 min workout']},
  {'id': 'w017', 'name': 'Postpartum Recovery', 'goal': 'rehabilitation', 'level': 'beginner', 'durationWeeks': 12, 'sessionsPerWeek': 3, 'isPremium': false, 'imageUrl': 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800', 'description': 'Gentle postpartum program to rebuild core and pelvic floor safely.', 'exercises': ['Diaphragmatic breathing', 'Pelvic floor exercises', 'Gentle walking', 'Modified planks']},
  {'id': 'w018', 'name': 'CrossFit-Style WOD Pack', 'goal': 'endurance', 'level': 'advanced', 'durationWeeks': 8, 'sessionsPerWeek': 5, 'isPremium': true, 'imageUrl': 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800', 'description': '30 different WODs to keep training fresh and intense.', 'exercises': ['Fran: Thrusters + Pull-ups 21-15-9', 'Cindy: AMRAP 20 min', 'Murph: 1 mile + 100 pull-ups + 200 push-ups + 300 squats + 1 mile']},
  {'id': 'w019', 'name': 'Swimmer Dryland Training', 'goal': 'performance', 'level': 'intermediate', 'durationWeeks': 8, 'sessionsPerWeek': 3, 'isPremium': true, 'imageUrl': 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800', 'description': 'Strength and flexibility training to improve swimming performance.', 'exercises': ['Lat pulldowns 4x10', 'Tricep dips 3x15', 'Rotator cuff exercises', 'Hip flexibility drills']},
  {'id': 'w020', 'name': '7-Day Detox Movement', 'goal': 'general_fitness', 'level': 'beginner', 'durationWeeks': 1, 'sessionsPerWeek': 7, 'isPremium': false, 'imageUrl': 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800', 'description': 'Light daily movement to reset your body and kick-start healthy habits.', 'exercises': ['Morning walk 20 min', 'Gentle yoga 20 min', 'Evening stretching 15 min']},
];

final _tips = [
  {'id': 't001', 'title': 'Drink Water Before Meals', 'category': 'hydration', 'imageUrl': 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=800', 'content': 'Drinking 500ml of water 30 minutes before each meal can reduce calorie intake by up to 13% and aids digestion significantly.'},
  {'id': 't002', 'title': 'Eat Protein First', 'category': 'protein', 'imageUrl': 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800', 'content': 'Starting your meal with protein signals fullness faster, stabilizes blood sugar, and reduces overall calorie consumption throughout the day.'},
  {'id': 't003', 'title': 'The 80% Rule', 'category': 'mindful-eating', 'imageUrl': 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800', 'content': 'Eat until 80% full (Hara Hachi Bu). It takes 20 minutes for the stomach to signal fullness to the brain — stop before you feel stuffed.'},
  {'id': 't004', 'title': 'Color Your Plate', 'category': 'vegetables', 'imageUrl': 'https://images.unsplash.com/photo-1512003867696-6d5ce6835040?w=800', 'content': 'Aim for 5 different colored vegetables daily. Each color provides different phytonutrients and antioxidants essential for optimal health.'},
  {'id': 't005', 'title': 'Meal Prep Sundays', 'category': 'meal-planning', 'imageUrl': 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800', 'content': 'Preparing meals in advance dramatically reduces fast food consumption and saves both money and time throughout the week.'},
  {'id': 't006', 'title': 'Healthy Fats Are Essential', 'category': 'fats', 'imageUrl': 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800', 'content': 'Avocados, olive oil, nuts and fatty fish support brain function, hormone production and help absorb fat-soluble vitamins A, D, E, K.'},
  {'id': 't007', 'title': 'Fiber Keeps You Full', 'category': 'fiber', 'imageUrl': 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=800', 'content': 'Adults need 25-38g of fiber daily. Fiber slows digestion, feeds gut bacteria, and reduces the risk of heart disease and diabetes.'},
  {'id': 't008', 'title': 'Post-Workout Protein Window', 'category': 'protein', 'imageUrl': 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800', 'content': 'Consume 20-40g of protein within 2 hours after training to maximize muscle protein synthesis and recovery.'},
  {'id': 't009', 'title': 'Limit Ultra-Processed Foods', 'category': 'education', 'imageUrl': 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800', 'content': 'Ultra-processed foods cause inflammation and are engineered to override satiety signals. Cook whole foods 80% of the time.'},
  {'id': 't010', 'title': 'Sleep Affects Weight', 'category': 'lifestyle', 'imageUrl': 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800', 'content': 'Poor sleep increases ghrelin (hunger hormone) by 15% and decreases leptin (fullness hormone). Aim for 7-9 hours nightly.'},
  {'id': 't011', 'title': 'Chew Slowly', 'category': 'mindful-eating', 'imageUrl': 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800', 'content': 'Chewing each bite 20-30 times improves digestion, reduces bloating, and helps you eat less by allowing fullness signals to register.'},
  {'id': 't012', 'title': 'Track Your Food', 'category': 'education', 'imageUrl': 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800', 'content': 'People who track food intake lose 50% more weight than those who do not. Awareness is the first step to better nutrition.'},
  {'id': 't013', 'title': 'Eat the Rainbow', 'category': 'vegetables', 'imageUrl': 'https://images.unsplash.com/photo-1512003867696-6d5ce6835040?w=800', 'content': 'Red, orange, yellow, green, blue and purple produce each contain unique compounds that fight disease and support immunity.'},
  {'id': 't014', 'title': 'Protein at Every Meal', 'category': 'protein', 'imageUrl': 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800', 'content': 'Aim for 20-30g of protein per meal to maintain muscle mass, boost metabolism and stay full between meals.'},
  {'id': 't015', 'title': 'Limit Liquid Calories', 'category': 'hydration', 'imageUrl': 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=800', 'content': 'Sodas, juices and alcohol add hundreds of hidden calories without satisfying hunger. Replace with water, herbal tea or black coffee.'},
  {'id': 't016', 'title': 'Time Your Carbs', 'category': 'carbohydrates', 'imageUrl': 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 'content': 'Eat most of your carbohydrates around your workout — before for energy and after for glycogen replenishment and recovery.'},
  {'id': 't017', 'title': 'Gut Health Matters', 'category': 'gut-health', 'imageUrl': 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800', 'content': 'Include fermented foods like yogurt, kefir, kimchi and sauerkraut daily. A healthy gut microbiome improves immunity, mood and metabolism.'},
  {'id': 't018', 'title': 'Do Not Skip Breakfast', 'category': 'meal-planning', 'imageUrl': 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800', 'content': 'A protein-rich breakfast reduces cravings, improves concentration and prevents overeating at lunch and dinner.'},
  {'id': 't019', 'title': 'Cook with Olive Oil', 'category': 'fats', 'imageUrl': 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800', 'content': 'Extra virgin olive oil is rich in oleocanthal, a natural anti-inflammatory compound as potent as ibuprofen in some studies.'},
  {'id': 't020', 'title': 'Plan Before You Shop', 'category': 'meal-planning', 'imageUrl': 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800', 'content': 'Shopping with a meal plan and a list reduces impulse buying of unhealthy foods and cuts grocery costs by up to 30%.'},
  {'id': 't021', 'title': 'Anti-Inflammatory Foods', 'category': 'immunity', 'imageUrl': 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=800', 'content': 'Berries, fatty fish, broccoli, avocado and turmeric reduce chronic inflammation, the root cause of most modern diseases.'},
  {'id': 't022', 'title': 'Intermittent Fasting Basics', 'category': 'meal-planning', 'imageUrl': 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800', 'content': 'The 16:8 method (eat in an 8-hour window, fast 16 hours) can improve insulin sensitivity and support fat loss without calorie counting.'},
  {'id': 't023', 'title': 'Magnesium for Recovery', 'category': 'micronutrients', 'imageUrl': 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=800', 'content': 'Over 75% of people are magnesium deficient. Eat dark leafy greens, nuts, seeds and dark chocolate to support sleep, recovery and energy.'},
  {'id': 't024', 'title': 'Portion Plate Method', 'category': 'education', 'imageUrl': 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=800', 'content': 'Fill half your plate with vegetables, one quarter with lean protein and one quarter with complex carbs for balanced nutrition every meal.'},
  {'id': 't025', 'title': 'Omega-3 for Brain Health', 'category': 'fats', 'imageUrl': 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800', 'content': 'Eat fatty fish 2-3 times per week or take a fish oil supplement. Omega-3s reduce depression risk, improve memory and fight inflammation.'},
  {'id': 't026', 'title': 'Never Eat in Front of Screens', 'category': 'mindful-eating', 'imageUrl': 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800', 'content': 'Distracted eating leads to consuming 25% more calories. Eating mindfully improves meal satisfaction and reduces overeating.'},
  {'id': 't027', 'title': 'Vitamin D from Sun and Food', 'category': 'micronutrients', 'imageUrl': 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 'content': 'Over 1 billion people are vitamin D deficient. Get 15-20 min of sun daily and eat fatty fish, egg yolks and fortified dairy.'},
  {'id': 't028', 'title': 'Stress Raises Cortisol', 'category': 'lifestyle', 'imageUrl': 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800', 'content': 'Chronic stress raises cortisol which drives fat storage in the abdomen. Meditation, walking and breathing exercises lower cortisol naturally.'},
  {'id': 't029', 'title': 'Snack Smart', 'category': 'meal-planning', 'imageUrl': 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=800', 'content': 'The best snacks combine protein and fiber: apple with almond butter, Greek yogurt with berries, hummus with vegetables or a boiled egg.'},
  {'id': 't030', 'title': 'Hydration and Performance', 'category': 'hydration', 'imageUrl': 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=800', 'content': 'Even 2% dehydration reduces cognitive performance by 10% and physical performance by 20%. Drink 35ml per kg of bodyweight daily.'},
];

final _coaches = [
  {'id': 'coach001', 'name': 'Sarah Martinez', 'role': 'coach', 'email': 'sarah.martinez@betteryou.app', 'specialization': 'Weight Loss & Nutrition', 'bio': 'Certified personal trainer and nutrition coach with 8 years experience helping clients lose over 5000 lbs combined. Specializes in sustainable lifestyle changes, not crash diets.', 'profileImageUrl': 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', 'rating': 4.9, 'reviewCount': 142, 'pricePerSession': 45.0, 'currency': 'USD', 'availableSlots': ['Monday 9am', 'Monday 2pm', 'Wednesday 10am', 'Friday 9am', 'Saturday 11am'], 'tags': ['weight-loss', 'nutrition', 'women-health'], 'isVerified': true, 'verificationStatus': 'approved', 'isFeatured': true, 'xp': 5000, 'level': 10},
  {'id': 'coach002', 'name': 'Marcus Johnson', 'role': 'coach', 'email': 'marcus.johnson@betteryou.app', 'specialization': 'Muscle Gain & Strength', 'bio': 'Former competitive bodybuilder turned coach. Helped 200+ clients build muscle naturally without steroids. Expert in progressive overload and meal timing for hypertrophy.', 'profileImageUrl': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'rating': 4.8, 'reviewCount': 98, 'pricePerSession': 55.0, 'currency': 'USD', 'availableSlots': ['Tuesday 8am', 'Tuesday 6pm', 'Thursday 8am', 'Thursday 6pm', 'Saturday 9am'], 'tags': ['muscle-gain', 'strength', 'bodybuilding'], 'isVerified': true, 'verificationStatus': 'approved', 'isFeatured': true, 'xp': 4200, 'level': 9},
  {'id': 'coach003', 'name': 'Amina Benali', 'role': 'coach', 'email': 'amina.benali@betteryou.app', 'specialization': 'Yoga & Mindful Wellness', 'bio': 'RYT-500 certified yoga instructor and holistic wellness coach. Integrates mindfulness, breathwork and gentle movement to reduce stress and improve body awareness.', 'profileImageUrl': 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', 'rating': 4.95, 'reviewCount': 76, 'pricePerSession': 40.0, 'currency': 'USD', 'availableSlots': ['Monday 7am', 'Wednesday 7am', 'Friday 7am', 'Sunday 9am'], 'tags': ['yoga', 'mindfulness', 'stress-relief', 'flexibility'], 'isVerified': true, 'verificationStatus': 'approved', 'isFeatured': false, 'xp': 3800, 'level': 8},
];

final _doctors = [
  {'id': 'doctor001', 'name': 'Dr. Karim Mansouri', 'role': 'doctor', 'email': 'dr.mansouri@betteryou.app', 'specialty': 'Sports Medicine & Nutrition', 'bio': 'Board-certified sports medicine physician with 12 years experience. Specializes in performance optimization, injury prevention and evidence-based nutrition therapy.', 'profileImageUrl': 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400', 'rating': 4.9, 'reviewCount': 203, 'consultationPrice': 80.0, 'currency': 'USD', 'availableSlots': ['Tuesday 10am', 'Thursday 10am', 'Thursday 2pm', 'Saturday 10am'], 'tags': ['sports-medicine', 'nutrition-therapy', 'injury'], 'isVerified': true, 'verificationStatus': 'approved', 'isFeatured': true, 'xp': 6000, 'level': 12},
  {'id': 'doctor002', 'name': 'Dr. Leila Cherif', 'role': 'doctor', 'email': 'dr.cherif@betteryou.app', 'specialty': 'Endocrinology & Metabolic Health', 'bio': 'Endocrinologist specializing in diabetes, thyroid disorders and metabolic syndrome. Uses a food-first approach to restore hormonal balance and metabolic health.', 'profileImageUrl': 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400', 'rating': 4.85, 'reviewCount': 167, 'consultationPrice': 90.0, 'currency': 'USD', 'availableSlots': ['Monday 11am', 'Wednesday 11am', 'Friday 11am', 'Friday 3pm'], 'tags': ['diabetes', 'thyroid', 'metabolic-health', 'hormones'], 'isVerified': true, 'verificationStatus': 'approved', 'isFeatured': false, 'xp': 7000, 'level': 14},
  {'id': 'doctor003', 'name': 'Dr. Omar Tabet', 'role': 'doctor', 'email': 'dr.tabet@betteryou.app', 'specialty': 'Gastroenterology & Gut Health', 'bio': 'Gastroenterologist and certified functional medicine doctor. Helps patients heal IBS, Crohn\'s disease, food intolerances and optimize gut microbiome through diet.', 'profileImageUrl': 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400', 'rating': 4.88, 'reviewCount': 134, 'consultationPrice': 85.0, 'currency': 'USD', 'availableSlots': ['Monday 2pm', 'Wednesday 2pm', 'Thursday 4pm', 'Saturday 11am'], 'tags': ['gut-health', 'ibs', 'microbiome', 'food-intolerance'], 'isVerified': true, 'verificationStatus': 'approved', 'isFeatured': false, 'xp': 6500, 'level': 13},
];
